#!/usr/bin/env bash
# WebDesign-ToolKit environment provisioner.
# Installs shared prerequisites, skills, and curated tools.
# Optional: Midscene.js + Puppeteer (prompted, or via flags/env).
# TOOLS.md is updated after every successful (or skipped) install step.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT_DIR"

AGENTS_SKILLS_DIR="$ROOT_DIR/.agents/skills"
VENDOR_DIR="$ROOT_DIR/vendor"
NPM_PREFIX="$VENDOR_DIR/npm-global"
VISUAL_DIR="$VENDOR_DIR/visual-testing"
TOOLS_MD="$ROOT_DIR/TOOLS.md"

INSTALL_VISUAL="${INSTALL_VISUAL_TESTING:-}"
NONINTERACTIVE=0
VISUAL_INSTALLED=0

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

log()  { printf '\n\033[1;34m==>\033[0m %s\n' "$*"; }
ok()   { printf '\033[1;32m✓\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m!\033[0m %s\n' "$*"; }
err()  { printf '\033[1;31m✗\033[0m %s\n' "$*" >&2; }

usage() {
  cat <<'EOF'
Usage: ./setup.sh [options]

Options:
  --with-visual-testing    Install optional Midscene.js + Puppeteer
  --skip-visual-testing    Skip optional Midscene.js + Puppeteer
  --yes, -y                Non-interactive (skip optional unless --with-visual-testing or
                           INSTALL_VISUAL_TESTING=1)
  -h, --help               Show this help

Environment:
  INSTALL_VISUAL_TESTING=1|0   Force include/exclude visual testing stack
  ORIGINKIT_API_KEY            Optional; used by Originkit CLI when fetching components
EOF
}

have() { command -v "$1" >/dev/null 2>&1; }

ensure_dir() { mkdir -p "$1"; }

# Use -g --prefix so binaries land in $NPM_PREFIX/bin (not only node_modules/.bin).
npm_local() {
  ensure_dir "$NPM_PREFIX"
  npm install -g --prefix "$NPM_PREFIX" "$@"
}

export PATH="$NPM_PREFIX/bin:$NPM_PREFIX/node_modules/.bin:$HOME/.local/bin:$PATH"

clone_or_update() {
  local repo="$1"
  local dest="$2"
  if [[ -d "$dest/.git" ]]; then
    log "Updating $(basename "$dest")"
    git -C "$dest" pull --ff-only || warn "Could not fast-forward $dest; keeping existing checkout"
  else
    log "Cloning $repo → $dest"
    rm -rf "$dest"
    git clone --depth 1 "$repo" "$dest"
  fi
}

resolve_bin() {
  local name="$1"
  if [[ -x "$NPM_PREFIX/bin/$name" ]]; then
    printf '%s' "$NPM_PREFIX/bin/$name"
    return 0
  fi
  if [[ -x "$NPM_PREFIX/node_modules/.bin/$name" ]]; then
    printf '%s' "$NPM_PREFIX/node_modules/.bin/$name"
    return 0
  fi
  if have "$name"; then
    command -v "$name"
  else
    printf 'not found on PATH'
  fi
}

# screenshot-to-code needs Python 3.10–3.12 for native wheels (Pillow / pillow-heif).
# On systems with only 3.13+, provision a managed 3.12 via uv.
ensure_poetry_python_for_stc() {
  local py_minor
  py_minor="$(python3 -c 'import sys; print(sys.version_info.minor)')"
  if [[ "$py_minor" -le 12 ]]; then
    return 0
  fi

  warn "System Python is 3.$((py_minor))+; screenshot-to-code needs ≤3.12 for native deps"

  if ! have uv; then
    log "Installing uv (Astral) to provision Python 3.12"
    curl -LsSf https://astral.sh/uv/install.sh | sh
    export PATH="$HOME/.local/bin:$PATH"
  fi

  if ! have uv; then
    warn "uv not available; screenshot-to-code backend may fail on this Python"
    return 1
  fi

  uv python install 3.12
  local py312
  py312="$(uv python find 3.12)"
  ok "Managed Python for STC: $py312"
  poetry env use "$py312"
  record_tool "uv / Python 3.12" "installed" "\`uv\` → $(resolve_bin uv); \`$(uv python find 3.12)\`" "Managed interpreter for screenshot-to-code Poetry env"
  return 0
}

prompt_visual() {
  if [[ -n "$INSTALL_VISUAL" ]]; then
    case "${INSTALL_VISUAL,,}" in
      1|y|yes|true) return 0 ;;
      *) return 1 ;;
    esac
  fi

  if [[ "$NONINTERACTIVE" -eq 1 ]] || [[ ! -t 0 ]]; then
    warn "Non-interactive session: skipping optional Midscene.js + Puppeteer"
    warn "Re-run with --with-visual-testing or INSTALL_VISUAL_TESTING=1 to include them"
    return 1
  fi

  local answer
  printf '\n'
  read -r -p "Install optional Midscene.js + Puppeteer for visual testing? [y/N] " answer
  case "${answer,,}" in
    y|yes) return 0 ;;
    *) return 1 ;;
  esac
}

# ---------------------------------------------------------------------------
# TOOLS.md — written incrementally after each install
# ---------------------------------------------------------------------------

init_tools_md() {
  {
    echo "# Installed Tools"
    echo
    echo "Generated by \`setup.sh\` on $(date -Iseconds 2>/dev/null || date)."
    echo
    echo "This file is **local and git-ignored**. It is updated after **each** install step."
    echo "Agents and humans should read it to discover binaries, skill paths, and vendor checkouts."
    echo
    echo "Refresh with:"
    echo
    echo '```bash'
    echo './setup.sh'
    echo '```'
    echo
    echo "| Tool / Skill | Status | Commands / binaries | Notes |"
    echo "| :--- | :--- | :--- | :--- |"
  } > "$TOOLS_MD"
  ok "Initialized $TOOLS_MD"
}

# Append one row immediately after an install/skip. Flushes to disk right away.
record_tool() {
  local name="$1" status="$2" cmds="$3" notes="$4"
  name="${name//|/\\|}"
  status="${status//|/\\|}"
  cmds="${cmds//|/\\|}"
  notes="${notes//|/\\|}"
  echo "| **${name}** | ${status} | ${cmds} | ${notes} |" >> "$TOOLS_MD"
  ok "TOOLS.md ← ${name} (${status})"
}

finalize_tools_md() {
  # Drop previous footer if re-running mid-file (idempotent-ish: append once at end)
  {
    echo
    echo "## Visual testing"
    echo
    if [[ "$VISUAL_INSTALLED" -eq 1 ]]; then
      echo "Midscene.js + Puppeteer were installed under \`vendor/visual-testing/\`."
    else
      echo "Midscene.js + Puppeteer were **not** installed. Re-run with \`./setup.sh --with-visual-testing\`."
    fi
    echo
    echo "## Quick paths"
    echo
    echo "- Agent skills: \`$AGENTS_SKILLS_DIR\`"
    echo "- Skills lockfile: \`$ROOT_DIR/skills-lock.json\`"
    echo "- Vendor checkouts: \`$VENDOR_DIR\`"
    echo "- Local npm CLIs: \`$NPM_PREFIX\` (add \`vendor/npm-global/bin\` to PATH)"
    if [[ "$VISUAL_INSTALLED" -eq 1 ]]; then
      echo "- Visual testing package: \`$VISUAL_DIR\`"
    fi
    echo "- Per-tool guides: \`docs/tools/*/SETUP.md\`"
    echo "- Architecture decisions: \`docs/ARCHITECTURE.md\` (generated by \`adrtools\` from \`docs/.adr\`)"
    echo
  } >> "$TOOLS_MD"
  ok "Finalized $TOOLS_MD"
}

install_agent_skill() {
  local repo="$1"
  local skill="$2"
  if ! have npx; then
    err "npx is required to install agent skills"
    exit 1
  fi
  if npx --yes skills add "$repo" --skill "$skill" -y; then
    ok "Installed $skill → .agents/skills/$skill"
    return 0
  fi
  warn "Failed to install skill $skill from $repo"
  return 1
}

# ---------------------------------------------------------------------------
# Args
# ---------------------------------------------------------------------------

while [[ $# -gt 0 ]]; do
  case "$1" in
    --with-visual-testing) INSTALL_VISUAL=1; shift ;;
    --skip-visual-testing) INSTALL_VISUAL=0; shift ;;
    --yes|-y) NONINTERACTIVE=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) err "Unknown option: $1"; usage; exit 1 ;;
  esac
done

# ---------------------------------------------------------------------------
# Start TOOLS.md early so partial runs still leave a useful inventory
# ---------------------------------------------------------------------------

log "Initializing TOOLS.md"
init_tools_md

# ---------------------------------------------------------------------------
# Prerequisites
# ---------------------------------------------------------------------------

log "Checking required prerequisites"

if ! have git; then
  err "git is required. Install git and re-run."
  exit 1
fi
ok "git: $(resolve_bin git)"
record_tool "Git" "installed" "\`git\` → $(resolve_bin git)" "System prerequisite"

if ! have curl; then
  err "curl is required. Install curl and re-run."
  exit 1
fi
ok "curl: $(resolve_bin curl)"
record_tool "curl" "installed" "\`curl\` → $(resolve_bin curl)" "System prerequisite"

if ! have node; then
  err "Node.js 18+ is required. Install Node.js and re-run."
  exit 1
fi

NODE_MAJOR="$(node -p "process.versions.node.split('.')[0]")"
if [[ "$NODE_MAJOR" -lt 18 ]]; then
  err "Node.js 18+ required (found $(node -v))"
  exit 1
fi
ok "node: $(node -v) ($(resolve_bin node))"
ok "npm: $(npm -v) ($(resolve_bin npm))"
record_tool "Node.js" "installed" "\`node\` $(node -v) → $(resolve_bin node); \`npm\` $(npm -v) → $(resolve_bin npm)" "Requires 18+"

if ! have pnpm; then
  log "Installing pnpm via corepack/npm"
  if have corepack; then
    corepack enable
    corepack prepare pnpm@latest --activate || npm install -g pnpm
  else
    npm install -g pnpm
  fi
fi
ok "pnpm: $(pnpm -v) ($(resolve_bin pnpm))"
record_tool "pnpm" "installed" "\`pnpm\` $(pnpm -v) → $(resolve_bin pnpm)" "JS package manager"

if ! have python3; then
  err "Python 3.10+ is required (screenshot-to-code backend)."
  exit 1
fi

PY_OK="$(python3 - <<'PY'
import sys
print(int(sys.version_info[:2] >= (3, 10)))
PY
)"
if [[ "$PY_OK" != "1" ]]; then
  err "Python 3.10+ required (found $(python3 --version 2>&1))"
  exit 1
fi
ok "python3: $(python3 --version 2>&1) ($(resolve_bin python3))"
record_tool "Python 3" "installed" "\`python3\` → $(resolve_bin python3) ($(python3 --version 2>&1))" "Requires 3.10+"

if ! have poetry; then
  log "Installing Poetry"
  curl -sSL https://install.python-poetry.org | python3 -
  export PATH="$HOME/.local/bin:$PATH"
fi
if ! have poetry; then
  err "Poetry install failed. Install manually: https://python-poetry.org/docs/#installation"
  exit 1
fi
ok "poetry: $(poetry --version 2>&1) ($(resolve_bin poetry))"
record_tool "Poetry" "installed" "\`poetry\` → $(resolve_bin poetry)" "screenshot-to-code backend"

ensure_dir "$VENDOR_DIR"
ensure_dir "$NPM_PREFIX"
export PATH="$NPM_PREFIX/bin:$HOME/.local/bin:$PATH"

# Remove legacy manual clone layout (superseded by skills CLI).
if [[ -d "$ROOT_DIR/SKILLS" ]]; then
  warn "Removing legacy SKILLS/ directory (skills now live in .agents/skills/)"
  rm -rf "$ROOT_DIR/SKILLS"
fi

# ---------------------------------------------------------------------------
# Agent skills → .agents/skills/ (via skills CLI)
# ---------------------------------------------------------------------------

log "Installing agent skills into .agents/skills/"
ensure_dir "$AGENTS_SKILLS_DIR"

if install_agent_skill "https://github.com/Leonxlnx/taste-skill" "design-taste-frontend"; then
  record_tool "Taste Skill" "installed" "\`.agents/skills/design-taste-frontend/\`; \`npx skills add https://github.com/Leonxlnx/taste-skill --skill design-taste-frontend\`" "Load before UI generation"
else
  record_tool "Taste Skill" "failed" "\`npx skills add https://github.com/Leonxlnx/taste-skill --skill design-taste-frontend\`" "See docs/tools/taste-skill/SETUP.md"
fi

if install_agent_skill "https://github.com/vercel-labs/agent-skills" "web-design-guidelines"; then
  record_tool "Vercel Guidelines" "installed" "\`.agents/skills/web-design-guidelines/\`; https://vercel.com/design/guidelines" "Fallback only"
else
  record_tool "Vercel Guidelines" "failed" "\`npx skills add https://github.com/vercel-labs/agent-skills --skill web-design-guidelines\`" "See docs/tools/vercel-guidelines/SETUP.md"
fi

# BrandBooker skill set (on-demand authorship; brandbook-review is mandatory on brand add/update)
log "Installing BrandBooker skill set"
BRANDBOOKER_REPO="https://github.com/zvorky/brandbooker"
BRANDBOOKER_OK=1
for skill in \
  brandbook-orchestrator \
  design-philosophy \
  brand-architecture \
  visual-identity \
  color-typography \
  human-interface \
  packaging-experience \
  brand-governance \
  brandbook-review
do
  if ! install_agent_skill "$BRANDBOOKER_REPO" "$skill"; then
    BRANDBOOKER_OK=0
  fi
done
if [[ "$BRANDBOOKER_OK" -eq 1 ]]; then
  record_tool "BrandBooker" "installed" "\`.agents/skills/{brandbook-orchestrator,brandbook-review,…}/\`; \`npx skills add https://github.com/zvorky/brandbooker --skill '*'\`" "On-demand except brandbook-review on brand add/update — see docs/tools/brandbooker/SETUP.md"
else
  record_tool "BrandBooker" "partial" "\`npx skills add https://github.com/zvorky/brandbooker --skill '*'\`" "One or more BrandBooker skills failed — see docs/tools/brandbooker/SETUP.md"
fi

if [[ -f "$ROOT_DIR/skills-lock.json" ]]; then
  record_tool "skills CLI" "installed" "\`npx skills ls\`; restore: \`npx skills experimental_install\`" "Lockfile: \`skills-lock.json\` (git-ignored)"
else
  record_tool "skills CLI" "partial" "\`npx skills ls\`" "skills-lock.json not found after skill install"
fi

# ---------------------------------------------------------------------------
# awesome-design-md
# ---------------------------------------------------------------------------

log "Installing awesome-design-md reference collection"
if clone_or_update "https://github.com/VoltAgent/awesome-design-md.git" "$VENDOR_DIR/awesome-design-md"; then
  record_tool "awesome-design-md" "installed" "\`vendor/awesome-design-md/\`" "Copy DESIGN.md into /BRANDS/{brand}/"
else
  record_tool "awesome-design-md" "failed" "\`git clone https://github.com/VoltAgent/awesome-design-md.git\`" "See docs/tools/awesome-design-md/SETUP.md"
fi

# Drop mistaken ADR CLI checkouts (adrtools is a host CLI, not a toolkit tool).
if [[ -d "$VENDOR_DIR/adr-tools" ]] || [[ -d "$VENDOR_DIR/adrtools" ]]; then
  warn "Removing leftover ADR CLI vendor checkouts (use system adrtools; see AGENTS.md)"
  rm -rf "$VENDOR_DIR/adr-tools" "$VENDOR_DIR/adrtools"
fi

# ---------------------------------------------------------------------------
# Originkit CLI
# ---------------------------------------------------------------------------

log "Installing Originkit CLI (local prefix: vendor/npm-global)"
if npm_local originkit; then
  ok "originkit: $(resolve_bin originkit)"
  record_tool "Originkit" "installed" "\`originkit\` → $(resolve_bin originkit); \`npx originkit@latest\`; local prefix \`vendor/npm-global/\`; MCP \`https://mcp.originkit.dev/mcp\`" "Set ORIGINKIT_API_KEY or \`originkit login\`"
else
  warn "Originkit local install failed; use \`npx originkit@latest\`"
  record_tool "Originkit" "failed" "\`npx originkit@latest\`" "Local npm prefix install failed"
fi

# ---------------------------------------------------------------------------
# shadcn CLI (Cult UI + Skiper UI registries)
# ---------------------------------------------------------------------------

log "Ensuring shadcn CLI availability (Cult UI / Skiper UI)"
if npm_local shadcn@latest; then
  ok "shadcn: $(resolve_bin shadcn)"
  record_tool "Cult UI" "installed (registry)" "\`pnpm dlx shadcn@latest add @cult-ui/<name>\`; \`shadcn\` → $(resolve_bin shadcn)" "Per-project under /BRANDS/.../Projects/"
  record_tool "Skiper UI" "installed (registry)" "\`pnpm dlx shadcn@latest add @skiper-ui/<name>\`; \`shadcn\` → $(resolve_bin shadcn)" "Attribution on free tier"
else
  warn "shadcn local install failed; use \`pnpm dlx shadcn@latest\`"
  record_tool "Cult UI" "partial (registry)" "\`pnpm dlx shadcn@latest add @cult-ui/<name>\`" "shadcn local install failed; dlx still works"
  record_tool "Skiper UI" "partial (registry)" "\`pnpm dlx shadcn@latest add @skiper-ui/<name>\`" "shadcn local install failed; dlx still works"
fi

# ---------------------------------------------------------------------------
# screenshot-to-code
# ---------------------------------------------------------------------------

log "Installing screenshot-to-code"
STC_BACKEND_OK=0
STC_FRONTEND_OK=0

if clone_or_update "https://github.com/abi/screenshot-to-code.git" "$VENDOR_DIR/screenshot-to-code"; then
  log "Installing screenshot-to-code backend (Poetry)"
  (
    cd "$VENDOR_DIR/screenshot-to-code/backend"
    ensure_poetry_python_for_stc || true
    poetry install --no-interaction
    # Preview Chromium for upstream tool only — not the toolkit test stack.
    poetry run playwright install chromium >/dev/null 2>&1 \
      || warn "Playwright Chromium for screenshot-to-code preview skipped (optional for first run)"
  ) && STC_BACKEND_OK=1 && ok "screenshot-to-code backend ready" \
    || warn "screenshot-to-code backend install failed"

  log "Installing screenshot-to-code frontend (pnpm)"
  (
    cd "$VENDOR_DIR/screenshot-to-code/frontend"
    pnpm install
  ) && STC_FRONTEND_OK=1 && ok "screenshot-to-code frontend ready" \
    || warn "screenshot-to-code frontend install failed"

  if [[ "$STC_BACKEND_OK" -eq 1 && "$STC_FRONTEND_OK" -eq 1 ]]; then
    record_tool "screenshot-to-code" "installed" "Backend: \`cd vendor/screenshot-to-code/backend && poetry run uvicorn main:app --reload --port 7001\` · Frontend: \`cd vendor/screenshot-to-code/frontend && pnpm dev\`" "API key in backend/.env"
  elif [[ "$STC_BACKEND_OK" -eq 1 || "$STC_FRONTEND_OK" -eq 1 ]]; then
    record_tool "screenshot-to-code" "partial" "\`vendor/screenshot-to-code/\` · backend=$STC_BACKEND_OK frontend=$STC_FRONTEND_OK" "See docs/tools/screenshot-to-code/SETUP.md"
  else
    record_tool "screenshot-to-code" "failed" "\`vendor/screenshot-to-code/\` (clone present)" "Poetry/pnpm install failed — often needs Python ≤3.12"
  fi
else
  warn "screenshot-to-code clone failed; skipping backend/frontend install"
  record_tool "screenshot-to-code" "failed" "\`git clone https://github.com/abi/screenshot-to-code.git\`" "See docs/tools/screenshot-to-code/SETUP.md"
fi

# ---------------------------------------------------------------------------
# Optional: Midscene.js + Puppeteer
# ---------------------------------------------------------------------------

if prompt_visual; then
  log "Installing optional Midscene.js + Puppeteer into vendor/visual-testing"
  ensure_dir "$VISUAL_DIR"
  cat > "$VISUAL_DIR/package.json" <<'EOF'
{
  "name": "webdesign-toolkit-visual-testing",
  "private": true,
  "type": "module",
  "scripts": {
    "test:smoke": "node ./smoke.mjs"
  },
  "devDependencies": {
    "@midscene/web": "latest",
    "dotenv": "latest",
    "puppeteer": "latest",
    "tsx": "latest"
  }
}
EOF

  cat > "$VISUAL_DIR/smoke.mjs" <<'EOF'
import puppeteer from "puppeteer";

const browser = await puppeteer.launch({ headless: true });
const page = await browser.newPage();
await page.goto("https://example.com");
console.log("puppeteer-ok:", await page.title());
await browser.close();
EOF

  VISUAL_PKGS_OK=0
  VISUAL_BROWSER_OK=0

  if (
    cd "$VISUAL_DIR"
    pnpm install
  ); then
    VISUAL_PKGS_OK=1
    ok "Visual testing npm packages installed"
    # Do not use warn as || fallback — warn returns 0 and would mask browser install failure.
    if (
      cd "$VISUAL_DIR"
      pnpm exec puppeteer browsers install chrome >/dev/null 2>&1 \
        || pnpm dlx puppeteer browsers install >/dev/null 2>&1
    ); then
      VISUAL_BROWSER_OK=1
      ok "Puppeteer browser binary installed"
    else
      warn "Puppeteer browser download failed; run manually: cd vendor/visual-testing && pnpm dlx puppeteer browsers install"
    fi
  else
    warn "Visual testing pnpm install failed"
  fi

  if [[ "$VISUAL_PKGS_OK" -eq 1 && "$VISUAL_BROWSER_OK" -eq 1 ]]; then
    VISUAL_INSTALLED=1
    ok "Visual testing stack ready at vendor/visual-testing"
    record_tool "Puppeteer" "installed (optional)" "\`cd vendor/visual-testing && pnpm test:smoke\`; \`pnpm exec puppeteer\`" "Browser binary via Puppeteer"
    record_tool "Midscene.js" "installed (optional)" "\`@midscene/web\` in \`vendor/visual-testing/\`; \`pnpm exec tsx\`" "Set MIDSCENE_MODEL_* env vars"
  elif [[ "$VISUAL_PKGS_OK" -eq 1 ]]; then
    warn "Visual testing packages installed but browser binary is missing"
    record_tool "Puppeteer" "partial (optional)" "\`cd vendor/visual-testing && pnpm dlx puppeteer browsers install\`" "npm packages ok; browser download failed"
    record_tool "Midscene.js" "partial (optional)" "\`@midscene/web\` in \`vendor/visual-testing/\`" "Usable only after Puppeteer browser install succeeds"
  else
    warn "Visual testing install failed"
    record_tool "Puppeteer" "failed (optional)" "\`./setup.sh --with-visual-testing\`" "pnpm install failed"
    record_tool "Midscene.js" "failed (optional)" "\`./setup.sh --with-visual-testing\`" "pnpm install failed"
  fi
else
  ok "Skipped optional Midscene.js + Puppeteer"
  record_tool "Puppeteer" "skipped (optional)" "\`./setup.sh --with-visual-testing\`" "https://pptr.dev/"
  record_tool "Midscene.js" "skipped (optional)" "\`./setup.sh --with-visual-testing\`" "https://midscenejs.com/"
fi

# ---------------------------------------------------------------------------
# Finalize
# ---------------------------------------------------------------------------

finalize_tools_md

log "Setup complete"
echo
echo "Next steps:"
echo "  1. Read TOOLS.md for installed binaries and paths"
echo "  2. Load skills from .agents/skills/ before generating UI"
echo "  3. Keep brand/project work in nested git repos under /BRANDS/ — never push them to the toolkit remote"
if [[ "$VISUAL_INSTALLED" -eq 0 ]]; then
  echo "  4. Optional visual testing: ./setup.sh --with-visual-testing"
fi
echo
